---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: notemaker
spec:
  selector:
    app: mongodb
    tier: database
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: notemaker
  labels:
    app: mongodb
    tier: database
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: database
  template:
    metadata:
      labels:
        app: mongodb
        tier: database
    spec:
      containers:
        - name: mongodb
          image: notemaker/mongodb:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 27017


