---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: notemaker 
spec:
  selector:
    app: mongo-express
    tier: database
  ports:
    - port: 80
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: notemaker
  labels:
    app: mongo-express
    tier: database
spec:
  selector:
    matchLabels:
      app: mongo-express
      tier: database
  template:
    metadata:
      labels:
        app: mongo-express
        tier: database
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongodb 

